'use client';
import { useEffect, useMemo, useState } from 'react';
import { saveAiProgram } from '@/app/(app)/programs/ai/actions';
import { AI_PROGRAM_DRAFT_KEY, type AiProgramDraft } from '@/lib/ai/draft';
import { buildAiProgramBase, type AiCatalogExercise } from '@/lib/ai/program';
import { CustomSelect } from './custom-select';

export function AiProgramReview({catalog}:{catalog:AiCatalogExercise[]}) {
  const[draft,setDraft]=useState<AiProgramDraft|null>(null),[error,setError]=useState<string|null>(null);
  useEffect(()=>{try{const raw=sessionStorage.getItem(AI_PROGRAM_DRAFT_KEY);if(!raw)throw new Error('Your generated draft is no longer available.');setDraft(JSON.parse(raw))}catch(caught){setError(caught instanceof Error?caught.message:'The draft could not be opened.')}},[]);
  const base=useMemo(()=>draft?buildAiProgramBase(draft.input):null,[draft]);
  if(error)return <main className="content native-page native-gradient-background"><section className="surface empty-state native-empty-state"><h1>Draft unavailable</h1><p>{error}</p><a className="primary button-link" href="/programs/ai">Generate another program</a></section></main>;
  if(!draft||!base)return <main className="content native-page native-gradient-background"><section className="surface empty-state native-empty-state" aria-live="polite"><p>Opening your program draft…</p></section></main>;
  const selectedByDay=new Map(draft.selection.days.map(day=>[day.dayIndex,day]));
  const updateSlot=(dayIndex:number,slotId:string,exerciseName:string)=>setDraft(current=>{if(!current)return current;return{...current,selection:{...current.selection,days:current.selection.days.map(day=>day.dayIndex!==dayIndex?day:{...day,selections:[...day.selections.filter(item=>item.slotId!==slotId),...(exerciseName?[{slotId,exerciseName,reason:'Selected during program review.'}]:[])]})}}});
  const complete=base.days.every(day=>{const selections=selectedByDay.get(day.dayIndex)?.selections??[],names=selections.map(item=>item.exerciseName);return day.slots.every(slot=>selections.some(item=>item.slotId===slot.id))&&new Set(names).size===names.length});
  return <main className="content ai-review native-page native-gradient-background"><a className="back-link" href="/programs/ai">← Change generation settings</a><header className="page-header native-page-header"><div><div className="eyebrow">REVIEW BEFORE SAVING</div><h1>{draft.input.name}</h1><p>Swap exercises freely. Removing one opens its rules-defined slot so you can add a replacement without changing prescribed volume.</p></div></header>
    <div className="stack native-list-stack">{base.days.map(day=>{const chosen=selectedByDay.get(day.dayIndex);return <section className="surface native-section" key={day.dayIndex}><h2>{chosen?.label??day.splitName}</h2><div className="review-exercises">{day.slots.map(slot=>{const item=chosen?.selections.find(selection=>selection.slotId===slot.id),exercise=catalog.find(option=>option.name===item?.exerciseName),options=catalog.filter(option=>option.muscleGroup===slot.muscle).map(option=>({value:option.name,label:`${option.name} · ${option.equipment??'Equipment not listed'}`}));return <article className={`${item?'review-exercise':'review-exercise empty'} native-list-card`} key={slot.id}><div><strong>{item?.exerciseName??`Add ${slot.muscle} exercise`}</strong><small>{slot.muscle} · {slot.role}{exercise?.equipment?` · ${exercise.equipment}`:''}</small><p>{slot.sets} × {slot.repsMin}–{slot.repsMax} · RIR {slot.rir}</p></div><div className="review-controls"><CustomSelect ariaLabel={`${item?'Swap':'Add'} ${slot.muscle} exercise`} value={item?.exerciseName??''} onChange={value=>updateSlot(day.dayIndex,slot.id,value)} options={[{value:'',label:item?'Choose a replacement…':'Choose an exercise…',disabled:true},...options]}/>{item&&<button type="button" className="danger compact" onClick={()=>updateSlot(day.dayIndex,slot.id,'')}>Delete</button>}</div></article>})}</div></section>})}</div>
    {!complete&&<p className="notice error" role="alert">Fill every rules-defined exercise slot before accepting the program.</p>}
    <form action={saveAiProgram} className="review-accept"><input type="hidden" name="input" value={JSON.stringify(draft.input)}/><input type="hidden" name="selection" value={JSON.stringify(draft.selection)}/><button className="primary full" disabled={!complete}>Accept and save program</button></form>
  </main>;
}
