import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth/require-user';
import { addProgramExercise, renameProgram, setCurrentProgram, softDeleteProgram } from '../actions';
import { CustomSelect } from '@/components/custom-select';
import { TemplateExerciseEditor } from '@/components/template-exercise-editor';

export default async function ProgramDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const{id}=await params,query=await searchParams,{supabase,user}=await requireUser();
  const{data:program,error}=await supabase.from('programs').select('id,name,total_weeks,days_per_week,is_current,focus').eq('id',id).eq('user_id',user.id).is('deleted_at',null).maybeSingle();
  if(error)throw new Error(`Could not load program: ${error.message}`);if(!program)notFound();
  const[{data:days,error:dayError},{data:catalog,error:catalogError}]=await Promise.all([
    supabase.from('program_days').select('id,week_number,day_number,label,completed,skipped,program_exercises(id,exercise_name,muscle_group,equipment,sort_order,target_sets,target_reps_min,target_reps_max,target_weight,rir)').eq('program_id',id).order('week_number').order('day_number'),
    supabase.from('exercises').select('id,name,muscle_group,equipment').order('name'),
  ]);
  if(dayError)throw new Error(`Could not load days: ${dayError.message}`);if(catalogError)throw new Error(`Could not load exercises: ${catalogError.message}`);
  const dayList=days??[],isComplete=dayList.length>0&&dayList.every(day=>day.completed||day.skipped);
  const weeks=Array.from({length:program.total_weeks},(_,index)=>({number:index+1,days:dayList.filter(day=>day.week_number===index+1)})),weekOne=weeks[0]?.days??[],nextDay=dayList.find(day=>!day.completed&&!day.skipped);
  return <main className="content"><a className="back-link" href="/programs">← Programs</a><header className="page-header"><div><div className="eyebrow">{program.focus}</div><h1>{program.name}</h1><p>{program.total_weeks} weeks · {program.days_per_week} days/week</p></div>{isComplete?<span className="pill">Complete</span>:program.is_current&&<span className="pill">Active</span>}</header>
    {query.error&&<p className="notice error" role="alert">{String(query.error)}</p>}
    <section className="surface program-settings"><form className="rename-program" action={renameProgram}><input type="hidden" name="id" value={id}/><label>Program name<input name="name" defaultValue={program.name} required/></label><button className="secondary">Rename</button></form><div className="program-action-row">{!program.is_current&&!isComplete&&<form action={setCurrentProgram}><input type="hidden" name="id" value={id}/><button>Make active</button></form>}<form action={softDeleteProgram}><input type="hidden" name="id" value={id}/><button className="danger">Delete program</button></form></div></section>
    <section className="surface schedule-board" aria-labelledby="schedule-title"><header><div><div className="eyebrow">SCHEDULE</div><h2 id="schedule-title">Program overview</h2></div><div className="schedule-legend"><span className="completed">Completed</span><span className="skipped">Skipped</span><span className="next">Up next</span></div></header><div className="schedule-scroll"><table><thead><tr><th>Week</th>{Array.from({length:program.days_per_week},(_,index)=><th key={index}>Day {index+1}</th>)}</tr></thead><tbody>{weeks.map(week=><tr key={week.number}><th><strong>{week.number}</strong><span>{week.days.filter(day=>day.completed).length}/{week.days.length}</span></th>{week.days.map(day=>{const status=day.completed?'completed':day.skipped?'skipped':day.id===nextDay?.id?'next':'not-started';return <td key={day.id}><div className={`schedule-day ${status}`}><strong>{day.label??`Day ${day.day_number}`}</strong><span>{status==='completed'?'Completed':status==='skipped'?'Skipped':status==='next'?'Up next':'Not started'}</span></div></td>})}</tr>)}</tbody></table></div></section>
    <details className="surface template-editor"><summary>Edit exercise template</summary><p>Swap within the same muscle group to preserve the program’s volume. Changes apply to matching future days.</p><div className="stack day-stack">{weekOne.map(day=><section className="template-day" key={day.id}><h2>{day.label??`Day ${day.day_number}`}</h2><div className="review-exercises">{[...(day.program_exercises??[])].sort((a,b)=>(a.sort_order??0)-(b.sort_order??0)).map(exercise=><TemplateExerciseEditor key={exercise.id} programId={id} exercise={exercise} catalog={catalog??[]}/>)}</div><details className="add-exercise"><summary>Add exercise</summary><form action={addProgramExercise} className="form-grid"><input type="hidden" name="programId" value={id}/><input type="hidden" name="dayId" value={day.id}/><label>Exercise<CustomSelect name="exerciseId" defaultValue={catalog?.[0]?.id??''} options={(catalog??[]).map(exercise=>({value:exercise.id,label:`${exercise.name} · ${exercise.equipment}`}))}/></label><label>Sets<input name="sets" type="number" min="1" max="10" defaultValue="3" required/></label><label>Rep minimum<input name="repsMin" type="number" min="1" max="100" defaultValue="8" required/></label><label>Rep maximum<input name="repsMax" type="number" min="1" max="100" defaultValue="12" required/></label><label>Starting weight<input name="weight" type="number" min="0" step="0.5" defaultValue="0" required/></label><label>Target RIR<input name="rir" type="number" min="0" max="5" defaultValue="3" required/></label><button>Add to day</button></form></details></section>)}</div></details>
  </main>;
}
