import type { SupabaseClient } from '@supabase/supabase-js';
import { getExerciseByName } from '@grit/data/exerciseDatabase';
import { getProgressionProfile } from '@grit/data/exerciseProgressionProfiles';
import { recommendProgression, type MusclePriority, type ProgressionContext, type ProgramFocus, type SessionPerformance, type SorenessLevel } from '@grit/rules/progressionEngine';
import { capSetsPerExercise, rampSets } from '@grit/rules/volumeRamp';
import { capSessionSets, getSessionMaxSets } from '@grit/rules/sessionTrimmer';
import { redistributeSorenessTrim } from '@grit/rules/volumeBudget';
import type { ExperienceLevel, SlotRole, WeekParams } from '@grit/types/program';
import { getLandmark } from '@grit/utils/volumeLandmarks';

type TemplateExercise={exercise_name:string;muscle_group:string|null;equipment:string|null;target_sets:number;target_reps_min:number|null;target_reps_max:number|null;target_weight:number|null;rir:number|null;role:string|null};
type ExerciseSession={date:string;sets:Array<{weight:number;reps:number;reported_rir:number|null}>};
function prescription(ex:TemplateExercise){if(!Number.isInteger(ex.target_reps_min)||!Number.isInteger(ex.target_reps_max)||!Number.isInteger(ex.rir))throw new Error(`Incomplete prescription for ${ex.exercise_name}`);return{repsMin:ex.target_reps_min!,repsMax:ex.target_reps_max!,rir:ex.rir!}}

async function templateExercises(db:SupabaseClient,programId:string,dayNumber:number):Promise<TemplateExercise[]>{
  const {data:day,error:dayError}=await db.from('program_days').select('id').eq('program_id',programId).eq('week_number',1).eq('day_number',dayNumber).maybeSingle();
  if(dayError)throw dayError;if(!day)return[];
  const {data,error}=await db.from('program_exercises').select('exercise_name,muscle_group,equipment,target_sets,target_reps_min,target_reps_max,target_weight,rir,role').eq('program_day_id',day.id).order('sort_order');
  if(error)throw error;return(data??[]) as TemplateExercise[];
}

async function exerciseSessions(db:SupabaseClient,userId:string,exerciseName:string,programId:string):Promise<ExerciseSession[]>{
  const {data:days,error:dayError}=await db.from('program_days').select('id').eq('program_id',programId);if(dayError)throw dayError;
  const dayIds=(days??[]).map((day)=>day.id);if(!dayIds.length)return[];
  const {data:workouts,error:workoutError}=await db.from('workouts').select('id,completed_at,program_day_id').eq('user_id',userId).in('program_day_id',dayIds).is('deleted_at',null).order('completed_at',{ascending:false});if(workoutError)throw workoutError;
  const workoutIds=(workouts??[]).map((workout)=>workout.id);if(!workoutIds.length)return[];
  const {data:sets,error:setError}=await db.from('workout_sets').select('workout_id,weight,reps,set_index,reported_rir').eq('exercise_name',exerciseName).eq('completed',true).in('workout_id',workoutIds).order('set_index');if(setError)throw setError;
  return(workouts??[]).map((workout)=>({date:workout.completed_at,sets:(sets??[]).filter((set)=>set.workout_id===workout.id).map((set)=>({weight:Number(set.weight),reps:set.reps,reported_rir:set.reported_rir}))})).filter((session)=>session.sets.length>0);
}

async function sorenessForWorkout(db:SupabaseClient,workoutId:string){const{data,error}=await db.from('workout_feedback').select('muscle_group,soreness').eq('workout_id',workoutId);if(error)throw error;return Object.fromEntries((data??[]).map((row)=>[row.muscle_group,row.soreness])) as Record<string,string|null>}

async function recoverySignals(db:SupabaseClient,userId:string,programId:string){
  const{data:days,error:dayError}=await db.from('program_days').select('id').eq('program_id',programId);if(dayError)throw dayError;const ids=(days??[]).map((d)=>d.id);if(!ids.length)return{consecutiveStillSore:{},restartAtAnchor:{}};
  const{data:workouts,error:workoutError}=await db.from('workouts').select('id,completed_at').eq('user_id',userId).in('program_day_id',ids).is('deleted_at',null).order('completed_at',{ascending:false});if(workoutError)throw workoutError;if(!workouts?.length)return{consecutiveStillSore:{},restartAtAnchor:{}};
  const{data:feedback,error:feedbackError}=await db.from('workout_feedback').select('workout_id,muscle_group,soreness').in('workout_id',workouts.map((w)=>w.id));if(feedbackError)throw feedbackError;
  const byWorkout=new Map<string,typeof feedback>();for(const row of feedback??[]){const rows=byWorkout.get(row.workout_id)??[];rows.push(row);byWorkout.set(row.workout_id,rows)}
  const responses:Record<string,Array<string|null>>={};for(const workout of workouts)for(const row of byWorkout.get(workout.id)??[])(responses[row.muscle_group]??=[]).push(row.soreness);
  const consecutiveStillSore:Record<string,number>={},restartAtAnchor:Record<string,boolean>={};for(const[muscle,values]of Object.entries(responses)){const index=values.findIndex((value)=>value!=='Still sore');const streak=index===-1?values.length:index;if(streak>0)consecutiveStillSore[muscle]=streak;restartAtAnchor[muscle]=values[0]!=='Still sore'&&values[1]==='Still sore'&&values[2]==='Still sore'}return{consecutiveStillSore,restartAtAnchor};
}

async function muscleFrequency(db:SupabaseClient,programId:string){const{data:days,error}=await db.from('program_days').select('id').eq('program_id',programId).eq('week_number',1);if(error)throw error;if(!days?.length)return{};const{data:exercises,error:exError}=await db.from('program_exercises').select('program_day_id,muscle_group').in('program_day_id',days.map((d)=>d.id));if(exError)throw exError;const map=new Map<string,Set<string>>();for(const ex of exercises??[]){if(!ex.muscle_group)continue;if(!map.has(ex.muscle_group))map.set(ex.muscle_group,new Set());map.get(ex.muscle_group)!.add(ex.program_day_id)}return Object.fromEntries([...map].map(([muscle,set])=>[muscle,set.size])) as Record<string,number>}

function anchors(muscle:string,priority:MusclePriority|undefined,frequency:number){const landmark=getLandmark(muscle);if(!landmark||frequency<=0)return null;const maintain=priority==='maintain';const week1=maintain?landmark.mv:landmark.mev;const peak=priority==='emphasize'||priority==='grow'?landmark.mav:week1;return{week1:week1/frequency,peak:peak/frequency,deload:landmark.mv/frequency}}

async function saveTargets(db:SupabaseClient,dayId:string,targets:Array<{exerciseName:string;sets:number;repsMin:number;repsMax:number;weightLbs:number;rir:number;rationale:string}>){if(!targets.length)return;const{error}=await db.from('program_day_targets').upsert(targets.map((target)=>({program_day_id:dayId,exercise_name:target.exerciseName,target_sets:target.sets,target_reps_min:target.repsMin,target_reps_max:target.repsMax,target_weight:target.weightLbs,rir:target.rir,ai_rationale:target.rationale})),{onConflict:'program_day_id,exercise_name'});if(error)throw error}

export async function computeProgression(db:SupabaseClient,userId:string,programDayId:string,experienceLevel:ExperienceLevel,workoutId:string){
  const{data:day,error:dayError}=await db.from('program_days').select('program_id,week_number,day_number').eq('id',programDayId).maybeSingle();if(dayError)throw dayError;if(!day)return;
  const{data:program,error:programError}=await db.from('programs').select('user_id,total_weeks,focus,muscle_priorities').eq('id',day.program_id).eq('user_id',userId).maybeSingle();if(programError)throw programError;if(!program)return;
  const exercises=await templateExercises(db,day.program_id,day.day_number);if(!exercises.length)return;const nextWeek=day.week_number+1;
  if(nextWeek<=program.total_weeks){
    const{data:nextDay,error}=await db.from('program_days').select('id').eq('program_id',day.program_id).eq('week_number',nextWeek).eq('day_number',day.day_number).maybeSingle();if(error)throw error;
    if(nextDay){const isDeload=nextWeek===program.total_weeks;const soreness=await sorenessForWorkout(db,workoutId);const recovery=await recoverySignals(db,userId,day.program_id);const enriched=await Promise.all(exercises.map(async(ex)=>{const all=await exerciseSessions(db,userId,ex.exercise_name,day.program_id);const sessions:SessionPerformance[]=all.map((s)=>({date:s.date,sets:s.sets.filter((set)=>set.reps>0).map((set)=>({weight:set.weight,reps:set.reps,rir:set.reported_rir??undefined}))})).filter((s)=>s.sets.length>0);return{ex,sessions,exerciseDef:getExerciseByName(ex.exercise_name),weight:sessions[0]?.sets.length??ex.target_sets}}));
      const byMuscle=new Map<string,typeof enriched>();for(const item of enriched){if(!item.ex.muscle_group)continue;if(!byMuscle.has(item.ex.muscle_group))byMuscle.set(item.ex.muscle_group,[]);byMuscle.get(item.ex.muscle_group)!.push(item)}
      const overrides=new Map<string,{trainingSets:number;deloadSets:number}>();if((program.focus??'hypertrophy')==='hypertrophy'){const frequencies=await muscleFrequency(db,day.program_id);const params:WeekParams={weekNumber:nextWeek,totalTrainingWeeks:Math.max(1,program.total_weeks-1),isDeload};for(const[muscle,items]of byMuscle){const frequency=frequencies[muscle];if(!frequency)continue;const anchor=anchors(muscle,program.muscle_priorities?.[muscle] as MusclePriority|undefined,frequency);if(!anchor)continue;const target=rampSets(anchor,params,soreness[muscle] as SorenessLevel|undefined);const deload=Math.max(1,Math.round(anchor.deload));const sum=items.reduce((total,item)=>total+item.weight,0);if(sum<=0)continue;for(const item of items){const share=item.weight/sum;overrides.set(item.ex.exercise_name,{trainingSets:capSetsPerExercise(Math.max(1,Math.round(target*share))),deloadSets:capSetsPerExercise(Math.max(1,Math.round(deload*share)))})}}}
      const trims=new Map<string,number>();for(const[muscle,items]of byMuscle){if(soreness[muscle]!=='Still sore')continue;const result=redistributeSorenessTrim(items.map((item)=>({exerciseName:item.ex.exercise_name,systemicFatigue:getProgressionProfile(item.exerciseDef).fatigueRating.systemicFatigue,currentSets:item.weight})),items.length);for(const[name,trim]of result)trims.set(name,trim)}
      const generated=(await Promise.all(enriched.map(async({ex,sessions,exerciseDef,weight})=>{const priority=ex.muscle_group?program.muscle_priorities?.[ex.muscle_group] as MusclePriority|undefined:undefined;const ctx:ProgressionContext={experienceLevel,isDeload,mesoWeek:nextWeek,totalMesoWeeks:program.total_weeks,soreness:ex.muscle_group?soreness[ex.muscle_group] as SorenessLevel|undefined:undefined,consecutiveStillSoreCount:ex.muscle_group?recovery.consecutiveStillSore[ex.muscle_group]??0:0,restartAtVolumeAnchor:ex.muscle_group?recovery.restartAtAnchor[ex.muscle_group]??false:false,programFocus:(program.focus??'hypertrophy') as ProgramFocus,musclePriority:priority,hypertrophyVolumeOverride:overrides.get(ex.exercise_name),sorenessTrimOverride:trims.get(ex.exercise_name)};const target=prescription(ex);const rec=recommendProgression({sets:weight,repsMin:target.repsMin,repsMax:target.repsMax,rir:target.rir,role:(ex.role??undefined) as SlotRole|undefined,exerciseType:exerciseDef?.exerciseType,hardRirFloor:exerciseDef?.hardRirFloor,equipment:ex.equipment??undefined,profile:getProgressionProfile(exerciseDef)},sessions,ctx);if(rec.action==='FIRST_SESSION'||rec.nextWeight===0)return null;return{exerciseName:ex.exercise_name,sets:rec.nextSets,repsMin:rec.nextRepsMin,repsMax:rec.nextRepsMax,weightLbs:rec.nextWeight,rir:rec.nextRir,rationale:rec.reason,role:(ex.role??'Primary') as SlotRole,musclePriority:(priority??'mev') as MusclePriority|'mev'}}))).filter((value):value is NonNullable<typeof value>=>value!==null);const capped=capSessionSets(generated,getSessionMaxSets((program.focus??'hypertrophy') as ProgramFocus)).map(({role:_role,musclePriority:_priority,...target})=>target);await saveTargets(db,nextDay.id,capped)}
  }
  const names=new Set(exercises.map((ex)=>ex.exercise_name));const{data:later,error:laterError}=await db.from('program_days').select('id,day_number').eq('program_id',day.program_id).eq('week_number',day.week_number).gt('day_number',day.day_number).eq('completed',false);if(laterError)throw laterError;for(const future of later??[]){const futureExercises=(await templateExercises(db,day.program_id,future.day_number)).filter((ex)=>names.has(ex.exercise_name));const targets=[];for(const ex of futureExercises){const sessions=await exerciseSessions(db,userId,ex.exercise_name,day.program_id);if(!sessions.length)continue;const weight=Math.max(...sessions[0].sets.map((set)=>set.weight));if(weight>0){const target=prescription(ex);targets.push({exerciseName:ex.exercise_name,sets:ex.target_sets,repsMin:target.repsMin,repsMax:target.repsMax,weightLbs:weight,rir:target.rir,rationale:'Pre-filled from earlier session this week.'})}}await saveTargets(db,future.id,targets)}
}
