-- Seed all exercises from exercise_database_final_described.csv
-- Uses NOT EXISTS to safely insert without creating duplicates

insert into exercises (name, muscle_group, equipment, is_custom)
select v.name, v.muscle_group, v.equipment, false
from (values
  -- ─── CHEST ────────────────────────────────────────────────────────────────
  ('Barbell Flat Bench Press',              'Chest', 'Barbell'),
  ('Dumbbell Flat Bench Press',             'Chest', 'Dumbbell'),
  ('Smith Machine Flat Bench Press',        'Chest', 'Smith Machine'),
  ('Machine Chest Press',                   'Chest', 'Machine'),
  ('Barbell Incline Bench Press',           'Chest', 'Barbell'),
  ('Dumbbell Incline Bench Press',          'Chest', 'Dumbbell'),
  ('Smith Machine Incline Bench Press',     'Chest', 'Smith Machine'),
  ('Incline Machine Chest Press',           'Chest', 'Machine'),
  ('Barbell Decline Bench Press',           'Chest', 'Barbell'),
  ('Dumbbell Decline Bench Press',          'Chest', 'Dumbbell'),
  ('Smith Machine Decline Bench Press',     'Chest', 'Smith Machine'),
  ('Dumbbell Flat Flyes',                   'Chest', 'Dumbbell'),
  ('Dumbbell Incline Flyes',                'Chest', 'Dumbbell'),
  ('Cable Crossover / Cable Flyes',         'Chest', 'Cable'),
  ('Pec Deck Machine',                      'Chest', 'Machine'),
  ('Free Motion Chest Fly',                 'Chest', 'Freemotion'),
  ('Push-ups',                              'Chest', 'Bodyweight'),
  ('Weighted Push-ups',                     'Chest', 'Bodyweight Loadable'),
  ('Chest Dips',                            'Chest', 'Bodyweight'),
  ('Weighted Chest Dips',                   'Chest', 'Bodyweight Loadable'),
  ('Barbell Floor Press',                   'Chest', 'Barbell'),
  ('Dumbbell Floor Press',                  'Chest', 'Dumbbell'),
  ('Smith Machine Floor Press',             'Chest', 'Smith Machine'),
  ('Guillotine Press',                      'Chest', 'Barbell'),
  ('Hex Press / Squeeze Press',             'Chest', 'Dumbbell'),
  ('Low to High Cable Crossover',           'Chest', 'Cable'),
  ('High to Low Cable Crossover',           'Chest', 'Cable'),
  ('Free Motion Chest Press',               'Chest', 'Freemotion'),
  ('Decline Machine Chest Press',           'Chest', 'Machine'),
  ('Bent-Forward Cable Crossovers',         'Chest', 'Cable'),
  ('Flat Bench Cable Crossovers',           'Chest', 'Cable'),
  ('Straight-Arm Pullovers',                'Chest', 'Dumbbell'),
  ('Rope Pulls (Chest)',                    'Chest', 'Cable'),
  ('One-Arm Cable Pulls',                   'Chest', 'Cable'),
  ('Close Grip Chins (Chest Focus)',        'Chest', 'Bodyweight'),
  ('Hanging Serratus Crunches',             'Chest', 'Bodyweight'),
  ('Hanging Dumbbell Rows (Chest Focus)',   'Chest', 'Dumbbell'),

  -- ─── BACK ─────────────────────────────────────────────────────────────────
  ('Barbell Deadlift',                      'Back', 'Barbell'),
  ('Dumbbell Deadlift',                     'Back', 'Dumbbell'),
  ('Smith Machine Deadlift',               'Back', 'Smith Machine'),
  ('Barbell Bent-Over Row',                 'Back', 'Barbell'),
  ('Dumbbell Bent-Over Row',                'Back', 'Dumbbell'),
  ('Smith Machine Bent-Over Row',          'Back', 'Smith Machine'),
  ('Pendlay Row',                           'Back', 'Barbell'),
  ('T-Bar Row',                             'Back', 'Barbell'),
  ('T-Bar Row Machine',                     'Back', 'Machine'),
  ('Pull-ups',                              'Back', 'Bodyweight'),
  ('Weighted Pull-ups',                     'Back', 'Bodyweight Loadable'),
  ('Chin-ups',                              'Back', 'Bodyweight'),
  ('Weighted Chin-ups',                     'Back', 'Bodyweight Loadable'),
  ('Assisted Pull-up Machine',              'Back', 'Machine'),
  ('Lat Pulldown',                          'Back', 'Cable'),
  ('Machine Lat Pulldown',                  'Back', 'Machine'),
  ('Free Motion Lat Pulldown',              'Back', 'Freemotion'),
  ('Seated Cable Row',                      'Back', 'Cable'),
  ('Seated Machine Row',                    'Back', 'Machine'),
  ('Single-Arm Dumbbell Row',               'Back', 'Dumbbell'),
  ('Dumbbell Pullover',                     'Back', 'Dumbbell'),
  ('Straight-Arm Cable Pulldown',           'Back', 'Cable'),
  ('Barbell Shrugs',                        'Back', 'Barbell'),
  ('Dumbbell Shrugs',                       'Back', 'Dumbbell'),
  ('Smith Machine Shrugs',                  'Back', 'Smith Machine'),
  ('Cable Shrugs',                          'Back', 'Cable'),
  ('Seal Row',                              'Back', 'Barbell'),
  ('Dumbbell Seal Row',                     'Back', 'Dumbbell'),
  ('Rack Pulls',                            'Back', 'Barbell'),
  ('Smith Machine Rack Pulls',              'Back', 'Smith Machine'),
  ('Meadows Row',                           'Back', 'Barbell'),
  ('Snatch-Grip Deadlift',                  'Back', 'Barbell'),
  ('Machine Pullover',                      'Back', 'Machine'),
  ('Single-Arm Cable Row',                  'Back', 'Cable'),
  ('Single-Arm Lat Pulldown',               'Back', 'Cable'),
  ('Kroc Row',                              'Back', 'Dumbbell'),
  ('Heavy Upright Rows',                    'Back', 'Barbell'),
  ('Wide-Grip Chins Behind the Neck',       'Back', 'Bodyweight'),
  ('Wide-Grip Chins to the Front',          'Back', 'Bodyweight'),
  ('Close-Grip Chins',                      'Back', 'Bodyweight'),
  ('Close-or Medium-Grip Pulldowns',        'Back', 'Cable'),
  ('Bent-Arm Pullovers with Barbell',       'Back', 'Barbell'),
  ('Hyperextensions',                       'Back', 'Bodyweight'),
  ('Weighted Hyperextensions',              'Back', 'Bodyweight Loadable'),

  -- ─── SHOULDERS ────────────────────────────────────────────────────────────
  ('Barbell Overhead Press',               'Shoulders', 'Barbell'),
  ('Dumbbell Overhead Press',              'Shoulders', 'Dumbbell'),
  ('Smith Machine Overhead Press',         'Shoulders', 'Smith Machine'),
  ('Machine Shoulder Press',               'Shoulders', 'Machine'),
  ('Arnold Press',                         'Shoulders', 'Dumbbell'),
  ('Dumbbell Lateral Raise',               'Shoulders', 'Dumbbell'),
  ('Cable Lateral Raise',                  'Shoulders', 'Cable'),
  ('Machine Lateral Raise',               'Shoulders', 'Machine'),
  ('Free Motion Lateral Raise',            'Shoulders', 'Freemotion'),
  ('Barbell Front Raise',                  'Shoulders', 'Barbell'),
  ('Dumbbell Front Raise',                 'Shoulders', 'Dumbbell'),
  ('Cable Front Raise',                    'Shoulders', 'Cable'),
  ('Reverse Pec Deck',                     'Shoulders', 'Machine'),
  ('Dumbbell Rear Delt Flyes',             'Shoulders', 'Dumbbell'),
  ('Cable Rear Delt Flyes',                'Shoulders', 'Cable'),
  ('Barbell Upright Row',                  'Shoulders', 'Barbell'),
  ('Dumbbell Upright Row',                 'Shoulders', 'Dumbbell'),
  ('Cable Upright Row',                    'Shoulders', 'Cable'),
  ('Smith Machine Upright Row',            'Shoulders', 'Smith Machine'),
  ('Face Pulls',                           'Shoulders', 'Cable'),
  ('Push Press',                           'Shoulders', 'Barbell'),
  ('Dumbbell Push Press',                  'Shoulders', 'Dumbbell'),
  ('Z-Press',                              'Shoulders', 'Barbell'),
  ('Dumbbell Z-Press',                     'Shoulders', 'Dumbbell'),
  ('Smith Machine Z-Press',               'Shoulders', 'Smith Machine'),
  ('Cable Lateral Raise (Behind Back)',    'Shoulders', 'Cable'),
  ('Leaning Dumbbell Lateral Raise',      'Shoulders', 'Dumbbell'),
  ('Single-Arm Cable Front Raise',        'Shoulders', 'Cable'),
  ('Seated Dumbbell Rear Delt Raise',     'Shoulders', 'Dumbbell'),
  ('Behind-the-Neck Press',               'Shoulders', 'Barbell'),
  ('Military Press',                       'Shoulders', 'Barbell'),
  ('Clean and Press',                      'Shoulders', 'Barbell'),
  ('Standing Lateral Raises',              'Shoulders', 'Dumbbell'),
  ('One-Arm Cross Cable Laterals',        'Shoulders', 'Cable'),
  ('One-Arm Side Cable Laterals',         'Shoulders', 'Cable'),
  ('Seated One-Arm Cross Cable Laterals', 'Shoulders', 'Cable'),
  ('Reverse Overhead Dumbbell Laterals',  'Shoulders', 'Dumbbell'),
  ('Seated Bent-Over Dumbbell Laterals',  'Shoulders', 'Dumbbell'),
  ('Standing Bent-Over Dumbbell Laterals','Shoulders', 'Dumbbell'),
  ('Bent-Over Cable Laterals',            'Shoulders', 'Cable'),
  ('Lying Side Laterals',                  'Shoulders', 'Dumbbell'),

  -- ─── TRICEPS ──────────────────────────────────────────────────────────────
  ('Close-Grip Barbell Bench Press',       'Triceps', 'Barbell'),
  ('Close-Grip Smith Machine Bench Press', 'Triceps', 'Smith Machine'),
  ('Barbell Skullcrushers',                'Triceps', 'Barbell'),
  ('Dumbbell Skullcrushers',               'Triceps', 'Dumbbell'),
  ('Cable Skullcrushers',                  'Triceps', 'Cable'),
  ('Overhead Dumbbell Tricep Extension',   'Triceps', 'Dumbbell'),
  ('Overhead Cable Tricep Extension',      'Triceps', 'Cable'),
  ('Overhead Barbell Tricep Extension',    'Triceps', 'Barbell'),
  ('Tricep Pushdown (Rope/Bar)',           'Triceps', 'Cable'),
  ('Free Motion Tricep Pushdown',          'Triceps', 'Freemotion'),
  ('Dumbbell Tricep Kickback',             'Triceps', 'Dumbbell'),
  ('Cable Tricep Kickback',                'Triceps', 'Cable'),
  ('Tricep Dips',                          'Triceps', 'Bodyweight'),
  ('Weighted Tricep Dips',                 'Triceps', 'Bodyweight Loadable'),
  ('Machine Tricep Dips',                  'Triceps', 'Machine'),
  ('Diamond Push-ups',                     'Triceps', 'Bodyweight'),
  ('Weighted Diamond Push-ups',            'Triceps', 'Bodyweight Loadable'),
  ('JM Press',                             'Triceps', 'Barbell'),
  ('Smith Machine JM Press',               'Triceps', 'Smith Machine'),
  ('Tate Press',                           'Triceps', 'Dumbbell'),
  ('Reverse Grip Tricep Pushdown',         'Triceps', 'Cable'),
  ('French Press',                         'Triceps', 'Barbell'),
  ('Single-Arm Cable Tricep Extension',    'Triceps', 'Cable'),
  ('Bench Dips',                           'Triceps', 'Bodyweight'),
  ('Weighted Bench Dips',                  'Triceps', 'Bodyweight Loadable'),
  ('Reverse Pressdowns',                   'Triceps', 'Cable'),
  ('Seated Triceps Presses',               'Triceps', 'Machine'),
  ('Standing Triceps Presses',             'Triceps', 'Barbell'),
  ('Lying Triceps Extensions',             'Triceps', 'Barbell'),
  ('Lying Dumbbell Extensions',            'Triceps', 'Dumbbell'),
  ('Lying Cross Face Triceps Extensions',  'Triceps', 'Dumbbell'),
  ('One-Arm Triceps Extensions',           'Triceps', 'Dumbbell'),
  ('Dips Behind Back',                     'Triceps', 'Bodyweight'),
  ('Fixed Bar Triceps Extensions',         'Triceps', 'Barbell'),

  -- ─── BICEPS ───────────────────────────────────────────────────────────────
  ('Barbell Bicep Curl',                   'Biceps', 'Barbell'),
  ('Dumbbell Bicep Curl',                  'Biceps', 'Dumbbell'),
  ('Cable Bicep Curl',                     'Biceps', 'Cable'),
  ('Machine Bicep Curl',                   'Biceps', 'Machine'),
  ('Free Motion Bicep Curl',               'Biceps', 'Freemotion'),
  ('Dumbbell Hammer Curl',                 'Biceps', 'Dumbbell'),
  ('Cable Hammer Curl',                    'Biceps', 'Cable'),
  ('Barbell Preacher Curl',                'Biceps', 'Barbell'),
  ('Dumbbell Preacher Curl',               'Biceps', 'Dumbbell'),
  ('Machine Preacher Curl',                'Biceps', 'Machine'),
  ('Cable Preacher Curl',                  'Biceps', 'Cable'),
  ('Concentration Curl',                   'Biceps', 'Dumbbell'),
  ('Barbell Reverse Curl',                 'Biceps', 'Barbell'),
  ('Dumbbell Reverse Curl',                'Biceps', 'Dumbbell'),
  ('Cable Reverse Curl',                   'Biceps', 'Cable'),
  ('Drag Curl',                            'Biceps', 'Barbell'),
  ('Dumbbell Drag Curl',                   'Biceps', 'Dumbbell'),
  ('Smith Machine Drag Curl',              'Biceps', 'Smith Machine'),
  ('Incline Dumbbell Curl',                'Biceps', 'Dumbbell'),
  ('Spider Curl',                          'Biceps', 'Dumbbell'),
  ('Barbell Spider Curl',                  'Biceps', 'Barbell'),
  ('Zottman Curl',                         'Biceps', 'Dumbbell'),
  ('Bayesian Curl',                        'Biceps', 'Cable'),
  ('High Cable Bicep Curl',                'Biceps', 'Cable'),
  ('Arm Blaster Curls',                    'Biceps', 'Barbell'),
  ('Cheat Curls',                          'Biceps', 'Barbell'),
  ('3-Part Curls (21s)',                   'Biceps', 'Barbell'),
  ('Alternate Dumbbell Curls',             'Biceps', 'Dumbbell'),
  ('Lying Dumbbell Curls',                 'Biceps', 'Dumbbell'),
  ('Two-Hand Cable Curls',                 'Biceps', 'Cable'),
  ('Cable Curls with Preacher Bench',      'Biceps', 'Cable'),
  ('Reverse Preacher Bench Curls',         'Biceps', 'Machine'),
  ('One-Arm Cable Reverse Curls',          'Biceps', 'Cable'),

  -- ─── QUADS ────────────────────────────────────────────────────────────────
  ('Barbell Back Squat',                   'Quads', 'Barbell'),
  ('Smith Machine Back Squat',             'Quads', 'Smith Machine'),
  ('Bodyweight Squat',                     'Quads', 'Bodyweight'),
  ('Barbell Front Squat',                  'Quads', 'Barbell'),
  ('Dumbbell Front Squat',                 'Quads', 'Dumbbell'),
  ('Smith Machine Front Squat',            'Quads', 'Smith Machine'),
  ('Dumbbell Goblet Squat',                'Quads', 'Dumbbell'),
  ('Barbell Split Squat',                  'Quads', 'Barbell'),
  ('Dumbbell Split Squat',                 'Quads', 'Dumbbell'),
  ('Smith Machine Split Squat',            'Quads', 'Smith Machine'),
  ('Bulgarian Split Squat',                'Quads', 'Bodyweight'),
  ('Weighted Bulgarian Split Squat',       'Quads', 'Bodyweight Loadable'),
  ('Barbell Lunge',                        'Quads', 'Barbell'),
  ('Dumbbell Lunge',                       'Quads', 'Dumbbell'),
  ('Walking Lunges',                       'Quads', 'Bodyweight'),
  ('Barbell Walking Lunges',               'Quads', 'Barbell'),
  ('Dumbbell Walking Lunges',              'Quads', 'Dumbbell'),
  ('Weighted Walking Lunges',              'Quads', 'Bodyweight Loadable'),
  ('Smith Machine Lunge',                  'Quads', 'Smith Machine'),
  ('Leg Press',                            'Quads', 'Machine'),
  ('Hack Squat Machine',                   'Quads', 'Machine'),
  ('Barbell Hack Squat',                   'Quads', 'Barbell'),
  ('Leg Extension',                        'Quads', 'Machine'),
  ('Zercher Squat',                        'Quads', 'Barbell'),
  ('Pistol Squats',                        'Quads', 'Bodyweight'),
  ('Weighted Pistol Squats',               'Quads', 'Bodyweight Loadable'),
  ('Sissy Squats',                         'Quads', 'Bodyweight'),
  ('Weighted Sissy Squats',                'Quads', 'Bodyweight Loadable'),
  ('Sissy Squat Machine',                  'Quads', 'Machine'),
  ('Belt Squat',                           'Quads', 'Machine'),
  ('Box Squat',                            'Quads', 'Barbell'),
  ('Smith Machine Box Squat',              'Quads', 'Smith Machine'),
  ('Heavy Squats',                         'Quads', 'Barbell'),
  ('Half Squats',                          'Quads', 'Barbell'),

  -- ─── HAMSTRINGS ───────────────────────────────────────────────────────────
  ('Barbell Romanian Deadlift (RDL)',       'Hamstrings', 'Barbell'),
  ('Dumbbell Romanian Deadlift (RDL)',      'Hamstrings', 'Dumbbell'),
  ('Smith Machine Romanian Deadlift (RDL)','Hamstrings', 'Smith Machine'),
  ('Barbell Stiff-Legged Deadlift',         'Hamstrings', 'Barbell'),
  ('Dumbbell Stiff-Legged Deadlift',        'Hamstrings', 'Dumbbell'),
  ('Smith Machine Stiff-Legged Deadlift',   'Hamstrings', 'Smith Machine'),
  ('Seated Leg Curl',                       'Hamstrings', 'Machine'),
  ('Lying Leg Curl',                        'Hamstrings', 'Machine'),
  ('Standing Single Leg Curl',              'Hamstrings', 'Machine'),
  ('Cable Leg Curl',                        'Hamstrings', 'Cable'),
  ('Glute-Ham Raise (GHR)',                 'Hamstrings', 'Bodyweight'),
  ('Weighted Glute-Ham Raise (GHR)',        'Hamstrings', 'Bodyweight Loadable'),
  ('Barbell Good Mornings',                 'Hamstrings', 'Barbell'),
  ('Smith Machine Good Mornings',           'Hamstrings', 'Smith Machine'),
  ('Barbell Deficit Romanian Deadlift',     'Hamstrings', 'Barbell'),
  ('Dumbbell Deficit Romanian Deadlift',    'Hamstrings', 'Dumbbell'),
  ('Barbell Single-Leg Romanian Deadlift',  'Hamstrings', 'Barbell'),
  ('Dumbbell Single-Leg Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('Cable Single-Leg Romanian Deadlift',    'Hamstrings', 'Cable'),
  ('Nordic Hamstring Curl',                 'Hamstrings', 'Bodyweight'),
  ('Weighted Nordic Hamstring Curl',        'Hamstrings', 'Bodyweight Loadable'),
  ('Reverse Hyperextension',                'Hamstrings', 'Machine'),
  ('Straight-Leg Deadlifts',                'Hamstrings', 'Barbell'),

  -- ─── GLUTES ───────────────────────────────────────────────────────────────
  ('Barbell Hip Thrust',                   'Glutes', 'Barbell'),
  ('Dumbbell Hip Thrust',                  'Glutes', 'Dumbbell'),
  ('Smith Machine Hip Thrust',             'Glutes', 'Smith Machine'),
  ('Machine Hip Thrust',                   'Glutes', 'Machine'),
  ('Glute Bridge',                         'Glutes', 'Bodyweight'),
  ('Weighted Glute Bridge',                'Glutes', 'Bodyweight Loadable'),
  ('Barbell Glute Bridge',                 'Glutes', 'Barbell'),
  ('Cable Pull-Through',                   'Glutes', 'Cable'),
  ('Cable Glute Kickback',                 'Glutes', 'Cable'),
  ('Machine Glute Kickback',               'Glutes', 'Machine'),
  ('Dumbbell Step-Ups',                    'Glutes', 'Dumbbell'),
  ('Barbell Step-Ups',                     'Glutes', 'Barbell'),
  ('Step-Ups',                             'Glutes', 'Bodyweight'),
  ('Weighted Step-Ups',                    'Glutes', 'Bodyweight Loadable'),
  ('Barbell B-Stance Hip Thrust',          'Glutes', 'Barbell'),
  ('Dumbbell B-Stance Hip Thrust',         'Glutes', 'Dumbbell'),
  ('Smith Machine B-Stance Hip Thrust',    'Glutes', 'Smith Machine'),
  ('Dumbbell Frog Pumps',                  'Glutes', 'Dumbbell'),
  ('Frog Pumps',                           'Glutes', 'Bodyweight'),
  ('Hip Abductor Machine',                 'Glutes', 'Machine'),
  ('Cable Hip Abduction',                  'Glutes', 'Cable'),
  ('Barbell Curtsy Lunge',                 'Glutes', 'Barbell'),
  ('Dumbbell Curtsy Lunge',                'Glutes', 'Dumbbell'),

  -- ─── CALVES ───────────────────────────────────────────────────────────────
  ('Standing Barbell Calf Raise',           'Calves', 'Barbell'),
  ('Standing Dumbbell Calf Raise',          'Calves', 'Dumbbell'),
  ('Standing Machine Calf Raise',           'Calves', 'Machine'),
  ('Standing Smith Machine Calf Raise',     'Calves', 'Smith Machine'),
  ('Standing Calf Raise',                   'Calves', 'Bodyweight'),
  ('Weighted Single-Leg Calf Raise',        'Calves', 'Bodyweight Loadable'),
  ('Seated Calf Raise',                     'Calves', 'Machine'),
  ('Seated Barbell Calf Raise',             'Calves', 'Barbell'),
  ('Seated Dumbbell Calf Raise',            'Calves', 'Dumbbell'),
  ('Donkey Calf Raise Machine',             'Calves', 'Machine'),
  ('Donkey Calf Raise',                     'Calves', 'Bodyweight'),
  ('Weighted Donkey Calf Raise',            'Calves', 'Bodyweight Loadable'),
  ('Leg Press Calf Raise',                  'Calves', 'Machine'),
  ('Rotary Calf Machine',                   'Calves', 'Machine'),
  ('Single-Leg Calf Raise',                 'Calves', 'Bodyweight'),
  ('Seated Smith Machine Calf Raise',       'Calves', 'Smith Machine'),
  ('Farmer''s Walk on Toes',                'Calves', 'Dumbbell'),
  ('Reverse Calf Raises',                   'Calves', 'Bodyweight'),

  -- ─── ABS ──────────────────────────────────────────────────────────────────
  ('Crunches',                              'Abs', 'Bodyweight'),
  ('Ab Crunch Machine',                     'Abs', 'Machine'),
  ('Cable Crunch',                          'Abs', 'Cable'),
  ('Plank',                                 'Abs', 'Bodyweight'),
  ('Weighted Plank',                        'Abs', 'Bodyweight Loadable'),
  ('Lying Leg Raises',                      'Abs', 'Bodyweight'),
  ('Weighted Lying Leg Raises',             'Abs', 'Bodyweight Loadable'),
  ('Hanging Leg Raises',                    'Abs', 'Bodyweight'),
  ('Weighted Hanging Leg Raises',           'Abs', 'Bodyweight Loadable'),
  ('Russian Twists',                        'Abs', 'Bodyweight'),
  ('Weighted Russian Twists',               'Abs', 'Bodyweight Loadable'),
  ('Ab Wheel Rollout',                      'Abs', 'Bodyweight'),
  ('Weighted Ab Wheel Rollout',             'Abs', 'Bodyweight Loadable'),
  ('Cable Woodchoppers',                    'Abs', 'Cable'),
  ('Free Motion Woodchoppers',              'Abs', 'Freemotion'),
  ('V-Ups',                                 'Abs', 'Bodyweight'),
  ('Weighted V-Ups',                        'Abs', 'Bodyweight Loadable'),
  ('Dragon Flags',                          'Abs', 'Bodyweight'),
  ('Dead Bugs',                             'Abs', 'Bodyweight'),
  ('Weighted Dead Bugs',                    'Abs', 'Bodyweight Loadable'),
  ('Toes-to-Bar',                           'Abs', 'Bodyweight'),
  ('Cable Pallof Press',                    'Abs', 'Cable'),
  ('Free Motion Pallof Press',              'Abs', 'Freemotion'),
  ('Bicycle Crunches',                      'Abs', 'Bodyweight'),
  ('Torso Twist Machine',                   'Abs', 'Machine'),
  ('Roman Chairs',                          'Abs', 'Bodyweight'),
  ('Twisting Crunches',                     'Abs', 'Bodyweight'),
  ('Reverse Crunches',                      'Abs', 'Bodyweight'),
  ('Hanging Reverse Crunches',              'Abs', 'Bodyweight'),
  ('Vertical Bench Crunches',               'Abs', 'Bodyweight'),
  ('Seated Leg Tucks',                      'Abs', 'Bodyweight'),
  ('Seated Twist',                          'Abs', 'Bodyweight'),
  ('Flat Bench Leg Raises',                 'Abs', 'Bodyweight'),
  ('Bent-Knee Flat Bench Leg Raises',       'Abs', 'Bodyweight'),
  ('Bent-Knee Incline Board Leg Raises',    'Abs', 'Bodyweight'),
  ('Bent-Knee Vertical Bench Leg Raise',    'Abs', 'Bodyweight'),
  ('Twisting Hanging Leg Raises',           'Abs', 'Bodyweight'),
  ('Side Leg Raises',                       'Abs', 'Bodyweight'),
  ('Bent-Knee Side Leg Raises',             'Abs', 'Bodyweight'),
  ('Front Kicks',                           'Abs', 'Bodyweight'),
  ('Bench Kickbacks',                       'Abs', 'Bodyweight'),
  ('Rear Leg Scissors',                     'Abs', 'Bodyweight'),
  ('Vacuums',                               'Abs', 'Bodyweight'),

  -- ─── FOREARMS ─────────────────────────────────────────────────────────────
  ('Barbell Wrist Curls',                  'Forearms', 'Barbell'),
  ('Dumbbell One-Arm Wrist Curls',         'Forearms', 'Dumbbell'),
  ('Behind-the-Back Wrist Curls',          'Forearms', 'Barbell'),
  ('Reverse Wrist Curls with Barbell',     'Forearms', 'Barbell'),
  ('Reverse Wrist Curls with Dumbbells',   'Forearms', 'Dumbbell')

) as v(name, muscle_group, equipment)
where not exists (
  select 1 from exercises e
  where e.name = v.name and e.equipment = v.equipment
);
