-- EXERCISES TABLE
create table exercises (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  muscle_group text,
  equipment text,
  is_custom boolean default false,
  created_at timestamp default now()
);

-- SEED DATA (Arnold encyclopedia + common exercises)
insert into exercises (name, muscle_group, equipment) values
-- CHEST
('Barbell Bench Press', 'Chest', 'Barbell'),
('Incline Barbell Bench Press', 'Chest', 'Barbell'),
('Decline Barbell Bench Press', 'Chest', 'Barbell'),
('Dumbbell Bench Press', 'Chest', 'Dumbbell'),
('Incline Dumbbell Press', 'Chest', 'Dumbbell'),
('Decline Dumbbell Press', 'Chest', 'Dumbbell'),
('Dumbbell Flyes', 'Chest', 'Dumbbell'),
('Incline Dumbbell Flyes', 'Chest', 'Dumbbell'),
('Cable Crossover', 'Chest', 'Cable'),
('High-to-Low Cable Fly', 'Chest', 'Cable'),
('Low-to-High Cable Fly', 'Chest', 'Cable'),
('Pec Deck Fly', 'Chest', 'Machine'),
('Machine Chest Press', 'Chest', 'Machine'),
('Chest Dips', 'Chest', 'Bodyweight'),
('Push-Up', 'Chest', 'Bodyweight'),
('Weighted Push-Up', 'Chest', 'Bodyweight Loadable'),
('Smith Machine Bench Press', 'Chest', 'Smith Machine'),
('Smith Machine Incline Press', 'Chest', 'Smith Machine'),
-- BACK
('Barbell Row (Bent Over)', 'Back', 'Barbell'),
('Barbell Row (Underhand Grip)', 'Back', 'Barbell'),
('T-Bar Row', 'Back', 'Barbell'),
('Seated Cable Row', 'Back', 'Cable'),
('Wide-Grip Lat Pulldown', 'Back', 'Cable'),
('Close-Grip Lat Pulldown', 'Back', 'Cable'),
('Single-Arm Cable Row', 'Back', 'Cable'),
('Straight-Arm Pulldown', 'Back', 'Cable'),
('Pull-Up (Wide Grip)', 'Back', 'Bodyweight'),
('Pull-Up (Normal Grip)', 'Back', 'Bodyweight'),
('Chin-Up', 'Back', 'Bodyweight'),
('Weighted Pull-Up', 'Back', 'Bodyweight Loadable'),
('Dumbbell Row (Single-Arm)', 'Back', 'Dumbbell'),
('Dumbbell Row (Supported)', 'Back', 'Dumbbell'),
('Chest-Supported Machine Row', 'Back', 'Machine'),
('Machine Row', 'Back', 'Machine'),
('Deadlift', 'Back', 'Barbell'),
('Rack Pull', 'Back', 'Barbell'),
('Good Morning', 'Back', 'Barbell'),
('Hyperextension', 'Back', 'Bodyweight'),
('Weighted Hyperextension', 'Back', 'Bodyweight Loadable'),
-- SHOULDERS
('Barbell Overhead Press', 'Shoulders', 'Barbell'),
('Seated Dumbbell Press', 'Shoulders', 'Dumbbell'),
('Standing Dumbbell Press', 'Shoulders', 'Dumbbell'),
('Arnold Press', 'Shoulders', 'Dumbbell'),
('Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell'),
('Cable Lateral Raise', 'Shoulders', 'Cable'),
('Dumbbell Front Raise', 'Shoulders', 'Dumbbell'),
('Cable Front Raise', 'Shoulders', 'Cable'),
('Bent-Over Rear Delt Fly', 'Shoulders', 'Dumbbell'),
('Reverse Pec Deck', 'Shoulders', 'Machine'),
('Face Pull', 'Shoulders', 'Cable'),
('Machine Shoulder Press', 'Shoulders', 'Machine'),
('Smith Machine Overhead Press', 'Shoulders', 'Smith Machine'),
('Barbell Upright Row', 'Shoulders', 'Barbell'),
('Dumbbell Upright Row', 'Shoulders', 'Dumbbell'),
-- BICEPS
('Barbell Curl', 'Biceps', 'Barbell'),
('EZ-Bar Curl', 'Biceps', 'Barbell'),
('Dumbbell Curl (Alternating)', 'Biceps', 'Dumbbell'),
('Dumbbell Curl (Both Arms)', 'Biceps', 'Dumbbell'),
('Hammer Curl', 'Biceps', 'Dumbbell'),
('Concentration Curl', 'Biceps', 'Dumbbell'),
('Incline Dumbbell Curl', 'Biceps', 'Dumbbell'),
('Preacher Curl (Barbell)', 'Biceps', 'Barbell'),
('Preacher Curl (Dumbbell)', 'Biceps', 'Dumbbell'),
('Cable Curl', 'Biceps', 'Cable'),
('Cable Hammer Curl', 'Biceps', 'Cable'),
('Machine Curl', 'Biceps', 'Machine'),
-- TRICEPS
('Close-Grip Bench Press', 'Triceps', 'Barbell'),
('Skull Crusher (Barbell)', 'Triceps', 'Barbell'),
('Skull Crusher (EZ-Bar)', 'Triceps', 'Barbell'),
('Tricep Pushdown (Rope)', 'Triceps', 'Cable'),
('Tricep Pushdown (Bar)', 'Triceps', 'Cable'),
('Overhead Tricep Extension (Cable)', 'Triceps', 'Cable'),
('Overhead Tricep Extension (Dumbbell)', 'Triceps', 'Dumbbell'),
('Tricep Dips', 'Triceps', 'Bodyweight'),
('Weighted Tricep Dips', 'Triceps', 'Bodyweight Loadable'),
('Dumbbell Kickback', 'Triceps', 'Dumbbell'),
('Machine Tricep Extension', 'Triceps', 'Machine'),
-- FOREARMS
('Barbell Wrist Curl', 'Forearms', 'Barbell'),
('Dumbbell Wrist Curl', 'Forearms', 'Dumbbell'),
('Reverse Barbell Curl', 'Forearms', 'Barbell'),
('Reverse Dumbbell Curl', 'Forearms', 'Dumbbell'),
('Farmer''s Walk', 'Forearms', 'Dumbbell'),
('Barbell Wrist Extension', 'Forearms', 'Barbell'),
('Dumbbell Bench Wrist Curl', 'Forearms', 'Dumbbell'),
-- QUADS
('Barbell Back Squat', 'Quads', 'Barbell'),
('Barbell Front Squat', 'Quads', 'Barbell'),
('Leg Press', 'Quads', 'Machine'),
('Hack Squat', 'Quads', 'Machine'),
('Leg Extension', 'Quads', 'Machine'),
('Dumbbell Lunge', 'Quads', 'Dumbbell'),
('Barbell Lunge', 'Quads', 'Barbell'),
('Bulgarian Split Squat', 'Quads', 'Dumbbell'),
('Step-Up', 'Quads', 'Dumbbell'),
('Smith Machine Squat', 'Quads', 'Smith Machine'),
('Goblet Squat', 'Quads', 'Dumbbell'),
('Sissy Squat', 'Quads', 'Bodyweight'),
-- HAMSTRINGS
('Romanian Deadlift (Barbell)', 'Hamstrings', 'Barbell'),
('Romanian Deadlift (Dumbbell)', 'Hamstrings', 'Dumbbell'),
('Stiff-Leg Deadlift', 'Hamstrings', 'Barbell'),
('Lying Leg Curl', 'Hamstrings', 'Machine'),
('Seated Leg Curl', 'Hamstrings', 'Machine'),
('Standing Leg Curl', 'Hamstrings', 'Machine'),
('Nordic Hamstring Curl', 'Hamstrings', 'Bodyweight'),
('Good Morning (Hamstring Focus)', 'Hamstrings', 'Barbell'),
('Sumo Deadlift', 'Hamstrings', 'Barbell'),
-- GLUTES
('Barbell Hip Thrust', 'Glutes', 'Barbell'),
('Dumbbell Hip Thrust', 'Glutes', 'Dumbbell'),
('Glute Bridge', 'Glutes', 'Bodyweight'),
('Cable Kickback', 'Glutes', 'Cable'),
('Cable Pull-Through', 'Glutes', 'Cable'),
('Bulgarian Split Squat (Glute Focus)', 'Glutes', 'Dumbbell'),
('Donkey Kick', 'Glutes', 'Bodyweight'),
('Hip Abduction Machine', 'Glutes', 'Machine'),
-- CALVES
('Standing Calf Raise', 'Calves', 'Machine'),
('Seated Calf Raise', 'Calves', 'Machine'),
('Leg Press Calf Raise', 'Calves', 'Machine'),
('Dumbbell Calf Raise', 'Calves', 'Dumbbell'),
('Single-Leg Calf Raise', 'Calves', 'Bodyweight'),
('Donkey Calf Raise', 'Calves', 'Bodyweight Loadable'),
-- ABS
('Crunch', 'Abs', 'Bodyweight'),
('Cable Crunch', 'Abs', 'Cable'),
('Hanging Leg Raise', 'Abs', 'Bodyweight'),
('Lying Leg Raise', 'Abs', 'Bodyweight'),
('Ab Wheel Rollout', 'Abs', 'Bodyweight'),
('Plank', 'Abs', 'Bodyweight'),
('Decline Sit-Up', 'Abs', 'Bodyweight'),
('Russian Twist', 'Abs', 'Bodyweight'),
('Weighted Russian Twist', 'Abs', 'Dumbbell'),
('Reaching Sit-Up', 'Abs', 'Bodyweight'),
('Dragon Flag', 'Abs', 'Bodyweight'),
('Pallof Press', 'Abs', 'Cable'),
('Dead Bug', 'Abs', 'Bodyweight'),
('V-Up', 'Abs', 'Bodyweight'),
-- TRAPS
('Barbell Shrug', 'Traps', 'Barbell'),
('Dumbbell Shrug', 'Traps', 'Dumbbell'),
('Cable Shrug', 'Traps', 'Cable'),
('Machine Shrug', 'Traps', 'Machine');
