-- Add description column to exercises
alter table exercises add column if not exists description text;

-- CHEST
update exercises set description = $$The king of chest movements. Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower to mid-chest, and press explosively. Keep shoulder blades retracted and feet flat on the floor.$$ where name = 'Barbell Bench Press';
update exercises set description = $$Targets the upper chest and front delts. Set bench to 30–45°, grip slightly wider than shoulder-width, and lower the bar to your upper chest. The angle shifts emphasis to the clavicular head of the pectoralis major.$$ where name = 'Incline Barbell Bench Press';
update exercises set description = $$Emphasizes the lower portion of the pecs. Set bench to -15 to -30°, secure your legs, and press the bar to your lower chest. Keep the shoulder blades pinched together throughout.$$ where name = 'Decline Barbell Bench Press';
update exercises set description = $$Allows greater range of motion than the barbell variation. Lie flat, press dumbbells from chest height to full lockout, letting them travel in a slight arc. Keep wrists neutral and elbows at roughly 45°.$$ where name = 'Dumbbell Bench Press';
update exercises set description = $$Hits the upper chest with a natural pressing path. Set the bench to 30–45°, press dumbbells from shoulder height to lockout above the chest. Control the descent for a full stretch at the bottom.$$ where name = 'Incline Dumbbell Press';
update exercises set description = $$Targets the lower pecs while reducing shoulder stress. With the bench declined, press the dumbbells from your lower chest to lockout. The longer range of motion versus the barbell version increases the stretch.$$ where name = 'Decline Dumbbell Press';
update exercises set description = $$Isolation movement for the chest. Lie flat, hold dumbbells above your chest with a slight elbow bend, and lower them in a wide arc until you feel a deep pec stretch. Bring them back together squeezing the chest.$$ where name = 'Dumbbell Flyes';
update exercises set description = $$Targets the upper chest via isolation. Set bench to 30–45° and perform the fly motion, lowering dumbbells in a wide arc to feel a stretch across the upper pecs, then contract to return.$$ where name = 'Incline Dumbbell Flyes';
update exercises set description = $$Cable fly for constant tension across the chest. Set pulleys at head height, step forward, and bring handles together in front of your chest in a hugging arc. Squeeze the pecs hard at the point of contraction.$$ where name = 'Cable Crossover';
update exercises set description = $$Emphasizes the lower chest using a downward pressing arc. Set pulleys high, hinge slightly forward, and pull handles down and together toward your hips. Feel the lower pec fibres fully contract.$$ where name = 'High-to-Low Cable Fly';
update exercises set description = $$Targets the upper chest with an upward arc. Set pulleys low, step forward, and sweep handles upward and together at eye level. Focus on the squeeze at the top of the movement.$$ where name = 'Low-to-High Cable Fly';
update exercises set description = $$Machine isolation for the chest. Sit with back flat, place forearms on pads or grip handles, and bring the arms together in front of the chest. Control the stretch on the way out to maximize the hypertrophy stimulus.$$ where name = 'Pec Deck Fly';
update exercises set description = $$A guided press for the chest with reduced stabilizer demand. Adjust the seat so handles are at mid-chest level, press to full extension, and control the return. Great for drop sets and high-rep work.$$ where name = 'Machine Chest Press';
update exercises set description = $$Bodyweight compound movement for the lower chest and triceps. Lean slightly forward on parallel bars, lower until elbows reach ~90°, then press back to lockout. Forward lean increases pec involvement.$$ where name = 'Chest Dips';
update exercises set description = $$Classic bodyweight chest movement. From a plank position, lower your chest to the floor keeping elbows at about 45°, then press back up. Maintain a rigid core throughout and achieve a full chest stretch at the bottom.$$ where name = 'Push-Up';
update exercises set description = $$A progression of the standard push-up with added load. Place a plate on your upper back or use a weighted vest. Same technique as a regular push-up — full range of motion with a rigid body line.$$ where name = 'Weighted Push-Up';
update exercises set description = $$A guided barbell press useful for learning the movement or pushing to failure safely. Set the bar at mid-chest level when lying down, unrack, lower with control, and press to lockout. The fixed bar path requires slightly adjusted grip positioning.$$ where name = 'Smith Machine Bench Press';
update exercises set description = $$An incline chest press on the Smith machine. Set the bench to 30–45° and position it so the bar tracks over your upper chest. Good option for isolating upper pecs when fatigue or shoulder issues limit free-weight pressing.$$ where name = 'Smith Machine Incline Press';

-- BACK
update exercises set description = $$Foundational back thickness movement. Hinge forward ~45°, keep back flat and neutral, pull bar to lower ribcage, and squeeze the lats hard at the top. Control the descent to keep tension on the back.$$ where name = 'Barbell Row (Bent Over)';
update exercises set description = $$Supinated grip row that increases bicep involvement and allows a longer range of motion. Pull the bar to your lower abdomen, keeping elbows tucked close to your sides. Heavier loads are typically possible compared to overhand.$$ where name = 'Barbell Row (Underhand Grip)';
update exercises set description = $$Compound back thickness movement. Straddle the bar or use a T-bar platform, grip with both hands, hinge forward, and row the weight to your lower chest. Squeeze the shoulder blades together at the top.$$ where name = 'T-Bar Row';
update exercises set description = $$Horizontal pull with constant cable tension. Sit upright, pull the handle to your lower abdomen, drive elbows back, and squeeze the lats. Let the weight stretch your scapulae forward at the start of each rep.$$ where name = 'Seated Cable Row';
update exercises set description = $$Targets lat width by pulling a bar from overhead to the upper chest. Grip outside shoulder-width, lean back slightly, and drive elbows down and back. Avoid using momentum — feel the lats stretch fully at the top.$$ where name = 'Wide-Grip Lat Pulldown';
update exercises set description = $$A narrower grip pulldown that increases range of motion and bicep contribution. Pull the bar to your upper chest while leaning back slightly and driving elbows to your sides. Great for lat thickness.$$ where name = 'Close-Grip Lat Pulldown';
update exercises set description = $$Unilateral row for balanced back development. Pull the handle to your hip while rotating the torso slightly, then reach forward to stretch the lat. Single-arm work helps identify and correct side-to-side imbalances.$$ where name = 'Single-Arm Cable Row';
update exercises set description = $$Isolation exercise for the lats. Stand at a cable machine, grip the bar with arms nearly straight, and pull it down from overhead to your thighs in a sweeping arc. Keeps the biceps out of the movement.$$ where name = 'Straight-Arm Pulldown';
update exercises set description = $$Bodyweight lat width builder. Start from a dead hang, pull your chest toward the bar by driving elbows down and back, and lower with control. Full range of motion maximizes lat development.$$ where name = 'Pull-Up (Wide Grip)';
update exercises set description = $$Shoulder-width overhand pull-up. Hang from the bar with hands just outside shoulder-width and pull your chin over the bar. Engages lats, rhomboids, and rear delts evenly.$$ where name = 'Pull-Up (Normal Grip)';
update exercises set description = $$Supinated-grip pull-up placing the biceps in a stronger position. Hang with palms facing you, pull your chin above the bar, and lower fully. Generally allows slightly more reps than standard pull-ups.$$ where name = 'Chin-Up';
update exercises set description = $$Add a dip belt, vest, or hold a dumbbell between your feet to progress pull-ups beyond bodyweight. Same technique as standard pull-ups — full hang to chin-over-bar — with the added load demanding greater lat and arm strength.$$ where name = 'Weighted Pull-Up';
update exercises set description = $$Unilateral back exercise. Place one knee and hand on a bench, row the dumbbell from a full hang to hip level, keeping elbow close to the body. Allows heavy loads and a strong contraction.$$ where name = 'Dumbbell Row (Single-Arm)';
update exercises set description = $$Both hands and chest supported on an incline bench, rowing a dumbbell in each hand simultaneously. Removes lower back stress, allowing focus purely on the lats and rhomboids.$$ where name = 'Dumbbell Row (Supported)';
update exercises set description = $$Lies chest-down on an incline pad to eliminate momentum and isolate the back. Pull handles to your sides, squeezing shoulder blades together. Excellent for targeting the mid and upper back.$$ where name = 'Chest-Supported Machine Row';
update exercises set description = $$A seated machine row for back thickness. Adjust the chest pad and seat, grip the handles, and pull to your torso. Machines provide a fixed path and easy weight adjustment for high-rep sets.$$ where name = 'Machine Row';
update exercises set description = $$The ultimate full-body strength movement. Bar over mid-foot, neutral spine, grip just outside legs, brace hard, then drive the floor away. Lock out by squeezing glutes at the top and lower under control.$$ where name = 'Deadlift';
update exercises set description = $$A partial-range deadlift starting from just below, at, or above the knee. Set the pins in a rack, hinge and grip as in a deadlift, and pull to lockout. Allows heavier loads and targets the top portion of the pull.$$ where name = 'Rack Pull';
update exercises set description = $$Hip hinge movement that loads the hamstrings and lower back. Place a barbell on your upper traps, push hips back, and lower your torso until nearly parallel to the floor, then drive hips forward to return. Keep the back flat and knees soft.$$ where name = 'Good Morning';
update exercises set description = $$Lower back and glute extension on a hyperextension bench. Secure ankles, lower your torso toward the floor, then raise back to neutral. Avoid hyperextending past parallel; focus on hamstrings and erectors.$$ where name = 'Hyperextension';
update exercises set description = $$A progression of the standard hyperextension with a plate held to the chest or behind the head. Increases erector and glute loading. Same technique — lower until a good stretch is felt, then extend back to neutral.$$ where name = 'Weighted Hyperextension';

-- SHOULDERS
update exercises set description = $$Compound shoulder movement. Press the bar from clavicle height to full lockout overhead, keeping the bar over your centre of mass. Brace the core, squeeze the glutes, and keep wrists stacked over elbows.$$ where name = 'Barbell Overhead Press';
update exercises set description = $$Overhead press variation with independent arm movement. Sit upright, press dumbbells from shoulder height to lockout above the head, and lower with control. Seated position reduces lower-back involvement.$$ where name = 'Seated Dumbbell Press';
update exercises set description = $$Standing dumbbell overhead press requiring more core stability than the seated version. Press both dumbbells overhead simultaneously and lower back to ear level. Engage core and glutes to avoid lumbar hyperextension.$$ where name = 'Standing Dumbbell Press';
update exercises set description = $$Developed by Arnold Schwarzenegger, this press combines a rotation with the pressing movement. Start with palms facing you at chin height, rotate outward as you press overhead, and reverse on the way down. Hits all three deltoid heads.$$ where name = 'Arnold Press';
update exercises set description = $$Isolation exercise for the medial deltoid. Hold dumbbells at your sides and raise them to shoulder height in a wide arc, leading with the elbows. Avoid shrugging; keep a slight forward lean for better medial delt targeting.$$ where name = 'Dumbbell Lateral Raise';
update exercises set description = $$Lateral raise with constant cable tension throughout the range of motion. Attach a handle to the low pulley, raise your arm to shoulder height, and lower with control. Superior tension curve compared to dumbbells.$$ where name = 'Cable Lateral Raise';
update exercises set description = $$Isolation for the anterior deltoid. Hold dumbbells at your thighs and raise them forward to shoulder height with a slight elbow bend. Alternate arms or raise both together. Avoid using momentum.$$ where name = 'Dumbbell Front Raise';
update exercises set description = $$Front raise with consistent cable tension. Attach a handle to the low pulley, stand facing away, and raise your arm forward to shoulder height. The cable maintains load at the bottom of the movement unlike a dumbbell.$$ where name = 'Cable Front Raise';
update exercises set description = $$Isolation for the posterior deltoid. Hinge forward at the hips, hold dumbbells hanging below your chest, and raise them out to the sides in a wide arc. Squeeze rear delts at the top and keep elbows soft.$$ where name = 'Bent-Over Rear Delt Fly';
update exercises set description = $$Machine rear delt fly. Sit facing the pad, grip the handles with arms nearly parallel to the floor, and pull them apart in a wide arc. Finish with shoulder blades squeezed together to fully contract the rear delts.$$ where name = 'Reverse Pec Deck';
update exercises set description = $$Cable exercise for rear delts and external rotators. Set the rope attachment at head height, grip with palms down, and pull the rope toward your face while flaring elbows out. Finish with a strong external rotation at the end.$$ where name = 'Face Pull';
update exercises set description = $$Guided overhead press on a plate-loaded or selectorized machine. Adjust the seat so handles sit at shoulder height, press to full extension overhead, and control the descent. Good for beginners and high-rep finishers.$$ where name = 'Machine Shoulder Press';
update exercises set description = $$Overhead press on a Smith machine, providing a guided bar path. Set the bench to upright or press standing, unrack at shoulder height, and press to lockout. The fixed path limits stabilizer involvement.$$ where name = 'Smith Machine Overhead Press';
update exercises set description = $$Compound shoulder and trap exercise. Grip the barbell narrow, stand upright, and pull the bar straight up along your body to chin level, flaring elbows high. Avoid wide grip to reduce shoulder impingement risk.$$ where name = 'Barbell Upright Row';
update exercises set description = $$Same movement as the barbell upright row but with dumbbells, allowing the hands to travel a natural path. Pull both dumbbells up along the torso to chin level with elbows high, then lower with control.$$ where name = 'Dumbbell Upright Row';

-- BICEPS
update exercises set description = $$Classic bicep mass builder. Stand with a shoulder-width grip, curl the bar from hip level to shoulder height while keeping upper arms stationary, and lower fully to a complete stretch. Avoid swinging to maintain tension.$$ where name = 'Barbell Curl';
update exercises set description = $$A curl variation using an angled EZ-bar that reduces wrist and elbow strain. Grip the inner angled portion, curl from full extension to the shoulder, and lower with control. Targets both bicep heads and brachialis.$$ where name = 'EZ-Bar Curl';
update exercises set description = $$Alternating single-arm dumbbell curl allowing a supinating twist at the top. Curl one arm at a time, rotating the wrist outward as you lift to fully contract the bicep. Alternate each rep.$$ where name = 'Dumbbell Curl (Alternating)';
update exercises set description = $$Bilateral dumbbell curl performed with both arms simultaneously. Start with palms facing up, curl to shoulder height keeping upper arms still, and lower with full extension each rep.$$ where name = 'Dumbbell Curl (Both Arms)';
update exercises set description = $$Neutral-grip curl that hits the brachialis and brachioradialis heavily. Keep palms facing each other throughout the movement and curl the dumbbell to shoulder height. Can be done alternating or simultaneously.$$ where name = 'Hammer Curl';
update exercises set description = $$Strict single-arm curl for peak bicep contraction. Sit on a bench, brace the back of your upper arm against your inner thigh, and curl the dumbbell to full contraction. Eliminates all momentum.$$ where name = 'Concentration Curl';
update exercises set description = $$Set an incline bench to 45–60°, lie back, and let the dumbbells hang behind your hips for a deep bicep stretch. Curl to shoulder height. The stretched starting position greatly increases the growth stimulus.$$ where name = 'Incline Dumbbell Curl';
update exercises set description = $$Barbell curl on a preacher bench that locks the upper arms in place. Lower the bar to full extension — do not let the elbows slam at the bottom — then curl to the top. Targets the lower bicep and removes cheating.$$ where name = 'Preacher Curl (Barbell)';
update exercises set description = $$Single-arm preacher curl with a dumbbell. Same setup as the barbell version but allows independent arm work and a slight supinating twist at the top for a stronger contraction.$$ where name = 'Preacher Curl (Dumbbell)';
update exercises set description = $$Bicep curl using a cable for constant tension throughout the full range. Attach a straight bar or rope to the low pulley, curl to shoulder height, and lower fully. The cable keeps load at the bottom of the rep unlike free weights.$$ where name = 'Cable Curl';
update exercises set description = $$Neutral-grip cable curl using a rope attachment. Face the cable stack, grip the rope with palms facing each other, and curl to chin height. The rope allows the hands to spread apart at the top for a unique contraction.$$ where name = 'Cable Hammer Curl';
update exercises set description = $$Selectorized bicep curl machine. Adjust the seat and pad height so your elbows rest comfortably, then curl the handles to full contraction and lower with control. Ideal for drop sets and training to fatigue safely.$$ where name = 'Machine Curl';

-- TRICEPS
update exercises set description = $$Tricep-dominant compound press. Grip the barbell slightly inside shoulder-width, lower it to your lower chest with elbows tracking close to the body, and press to full lockout. More shoulder-friendly than very narrow grips.$$ where name = 'Close-Grip Bench Press';
update exercises set description = $$Lying tricep extension with a barbell. Lie on a flat bench, hold the bar with a narrow grip above your face, bend only at the elbows to lower the bar toward your forehead, and extend back to lockout. Targets the long head.$$ where name = 'Skull Crusher (Barbell)';
update exercises set description = $$The EZ-bar version reduces wrist strain during the lying tricep extension. Same movement pattern as the barbell skull crusher — lower toward the forehead by bending at the elbows and press back to full extension.$$ where name = 'Skull Crusher (EZ-Bar)';
update exercises set description = $$Cable tricep isolation using a rope attachment. Stand at a high pulley, grip the rope with palms facing in, push down to full extension, and flare the rope handles apart at the bottom for a peak contraction.$$ where name = 'Tricep Pushdown (Rope)';
update exercises set description = $$Cable pushdown with a straight or angled bar. Grip the bar with hands shoulder-width, elbows tucked at your sides, push down to lockout, and resist the weight back up. Keep upper arms stationary throughout.$$ where name = 'Tricep Pushdown (Bar)';
update exercises set description = $$Cable extension that keeps the long head under maximum stretch. Face away from a high pulley, grip a rope above your head, and extend your forearms overhead to lockout. Keep upper arms close to your ears.$$ where name = 'Overhead Tricep Extension (Cable)';
update exercises set description = $$Dumbbell overhead extension for the long tricep head. Hold one dumbbell with both hands overhead, lower behind your head by bending at the elbows, and press back to full extension. Keep upper arms stationary.$$ where name = 'Overhead Tricep Extension (Dumbbell)';
update exercises set description = $$Bodyweight compound tricep exercise on parallel bars. Keep torso upright to emphasize triceps over chest, lower until elbows reach ~90°, and press back to lockout. Add weight once bodyweight becomes easy.$$ where name = 'Tricep Dips';
update exercises set description = $$Standard tricep dips with added resistance via a dip belt or vest. Upright torso and full range of motion. A key progressive overload tool for intermediate and advanced lifters.$$ where name = 'Weighted Tricep Dips';
update exercises set description = $$Tricep isolation via hip-hinge position. Hinge forward ~45°, upper arm parallel to the floor, extend the forearm back to lockout, and hold the contraction briefly. Control the return to maintain tension.$$ where name = 'Dumbbell Kickback';
update exercises set description = $$Guided tricep extension machine. Adjust seat so your elbows align with the pivot point, press or extend the handles to full lockout, and control the return. Excellent for high-rep work and burnout sets.$$ where name = 'Machine Tricep Extension';

-- FOREARMS
update exercises set description = $$Isolation exercise for the wrist flexors. Sit on a bench, rest forearms on your thighs with the barbell hanging at the wrists, and curl the wrists upward through full range. Lower until the bar rolls to the fingertips for maximum stretch.$$ where name = 'Barbell Wrist Curl';
update exercises set description = $$Same wrist flexor isolation as the barbell version but with independent arms. Rest one forearm on a bench or your thigh, let the dumbbell roll to the fingers, and curl back up. Better for addressing imbalances.$$ where name = 'Dumbbell Wrist Curl';
update exercises set description = $$Barbell curl with an overhand (pronated) grip targeting the brachioradialis and wrist extensors. Curl the bar from hip level to shoulder height without letting the wrists bend. Builds forearm thickness.$$ where name = 'Reverse Barbell Curl';
update exercises set description = $$Overhand-grip dumbbell curl for the brachioradialis and wrist extensors. Performs the same function as the reverse barbell curl with the added benefit of independent arm loading.$$ where name = 'Reverse Dumbbell Curl';
update exercises set description = $$Loaded carry for grip strength, traps, and full-body conditioning. Pick up heavy dumbbells or farmer handles, stand tall, and walk for a set distance or time. Crush the handles and keep shoulders packed down.$$ where name = $$Farmer's Walk$$;
update exercises set description = $$Isolation for the wrist extensor muscles on the top of the forearm. Sit with the back of your forearms resting on your thighs, hold a barbell with an overhand grip, and extend the wrists upward through full range.$$ where name = 'Barbell Wrist Extension';
update exercises set description = $$Wrist flexor curl performed with the forearm resting on a flat bench. Place forearm palm-up on the bench edge, lower the dumbbell via wrist extension for a stretch, then curl back up. Stable position allows focus on the movement.$$ where name = 'Dumbbell Bench Wrist Curl';

-- QUADS
update exercises set description = $$The foundational lower body movement. Bar on upper traps, feet shoulder-width, squat to parallel or below, and drive through your heels. Keep chest up and knees tracking over toes throughout the lift.$$ where name = 'Barbell Back Squat';
update exercises set description = $$Quad-dominant squat with the bar in a front rack position. Elbows high, torso more upright than back squat, squat to depth while keeping the bar over mid-foot. Demands greater mobility but reduces lower-back loading.$$ where name = 'Barbell Front Squat';
update exercises set description = $$Compound quad exercise on a machine with reduced spinal loading. Place feet shoulder-width at mid-platform height, lower the sled until knees reach ~90°, then press to near lockout. Foot placement adjusts quad vs. glute emphasis.$$ where name = 'Leg Press';
update exercises set description = $$Machine squat emphasizing quads. Shoulders under the pads, feet low on the platform to increase quad recruitment, lower to depth, and drive back up. Provides a deep quad stretch at the bottom.$$ where name = 'Hack Squat';
update exercises set description = $$Isolation exercise for the quadriceps. Seated on the machine, pad across the shins, extend legs to full lockout, and hold briefly. Lower with control for the eccentric. Best used as an accessory, not a primary movement.$$ where name = 'Leg Extension';
update exercises set description = $$Unilateral lower body movement for quads and glutes. Hold dumbbells at your sides, step forward and lower the rear knee toward the floor, then drive through the front heel to return. Keep torso upright throughout.$$ where name = 'Dumbbell Lunge';
update exercises set description = $$Barbell-loaded lunge for greater quad and glute stimulus. Bar on upper traps, step into a lunge, lower the rear knee, and drive through the front foot. Can be done in place or as walking lunges.$$ where name = 'Barbell Lunge';
update exercises set description = $$Rear-foot-elevated split squat — one of the most effective unilateral quad builders. Rear foot elevated on a bench, front foot far enough out to keep the shin vertical, lower until the rear knee nears the floor. Brutally effective.$$ where name = 'Bulgarian Split Squat';
update exercises set description = $$Unilateral compound movement for quads and glutes. Step onto a box or bench, drive through the heel of the elevated foot to stand, then lower with control. Loaded with dumbbells or a barbell for progressive overload.$$ where name = 'Step-Up';
update exercises set description = $$Squat performed in a Smith machine. The guided bar path allows the lifter to experiment with foot placement. Position feet slightly forward to shift load to the quads; maintain a controlled descent to depth.$$ where name = 'Smith Machine Squat';
update exercises set description = $$Squat holding a dumbbell or kettlebell at chest height. The front load naturally keeps the torso upright, making it excellent for teaching squat mechanics. Great for warm-up sets and high-rep quad work.$$ where name = 'Goblet Squat';
update exercises set description = $$A knee-dominant isolation squat. Stand with heels elevated or hold a support, lean back and push the knees forward over the toes while lowering the torso, then return. Heavily loads the quads through a long range of motion.$$ where name = 'Sissy Squat';

-- HAMSTRINGS
update exercises set description = $$Primary hamstring and glute builder via hip hinge. Hold the bar at hip level, push hips back while keeping the back flat and bar close to the legs, lower until a strong hamstring stretch is felt, then drive hips forward to return.$$ where name = 'Romanian Deadlift (Barbell)';
update exercises set description = $$The dumbbell version of the RDL allows a more natural hand path and greater range of motion. Same hip-hinge mechanics — hinge back, lower to shin level feeling the hamstring stretch, and return by driving the hips forward.$$ where name = 'Romanian Deadlift (Dumbbell)';
update exercises set description = $$Similar to the RDL but performed with straighter legs and the bar starting from the floor. Requires greater hamstring flexibility. Emphasizes hamstring length and the stretch-shortening cycle through the full range.$$ where name = 'Stiff-Leg Deadlift';
update exercises set description = $$Prone machine curl for the hamstrings. Lie face down, place pad just above the heels, and curl the weight toward your glutes. Contract hard at the top and lower slowly to maintain tension throughout.$$ where name = 'Lying Leg Curl';
update exercises set description = $$Seated machine that keeps the hip in a flexed position, placing the hamstrings under greater stretch. Curl the pad to full contraction and lower with control. The seated position increases long-head hamstring involvement.$$ where name = 'Seated Leg Curl';
update exercises set description = $$Single-leg curl in a standing position, good for balance and unilateral work. Curl the heel toward the glute, hold at peak contraction, and lower fully. Isolates one leg at a time for balanced development.$$ where name = 'Standing Leg Curl';
update exercises set description = $$One of the best eccentric hamstring exercises. Kneel with ankles secured, lower your body slowly toward the floor resisting with the hamstrings, catch yourself, and use your hands to push back up. Builds exceptional eccentric strength.$$ where name = 'Nordic Hamstring Curl';
update exercises set description = $$Barbell on the upper traps, moderate forward hinge until the torso approaches parallel, feeling a deep hamstring stretch before returning. Keeping the knees slightly bent isolates the hamstrings more than the erectors.$$ where name = 'Good Morning (Hamstring Focus)';
update exercises set description = $$Wide-stance deadlift with a more upright torso. Feet wider than shoulder-width with toes pointed out, grip the bar inside the legs, and drive the hips forward to lockout. Targets the hamstrings, glutes, and inner thighs.$$ where name = 'Sumo Deadlift';

-- GLUTES
update exercises set description = $$The gold-standard glute builder. Upper back on a bench, barbell over hip crease, drive hips up to full extension, and squeeze the glutes hard at the top. Keep the chin tucked and ribs down to avoid lumbar hyperextension.$$ where name = 'Barbell Hip Thrust';
update exercises set description = $$Hip thrust performed with a dumbbell held over the hip crease. Same mechanics as the barbell version — upper back on bench, drive hips to full extension. Easier to set up; good for beginners or when a barbell is unavailable.$$ where name = 'Dumbbell Hip Thrust';
update exercises set description = $$Floor-based hip extension that targets the glutes. Lie on your back, feet flat on the floor, drive hips up to full extension squeezing glutes, and lower. Can be loaded with a barbell, dumbbell, or band for progressive overload.$$ where name = 'Glute Bridge';
update exercises set description = $$Cable-loaded glute isolation. Attach an ankle cuff to the low pulley, face the stack, hinge slightly forward, and kick the leg back and up, squeezing the glute at full extension. Control the return.$$ where name = 'Cable Kickback';
update exercises set description = $$Hip hinge movement using a cable between the legs for constant tension. Face away from the low pulley, hinge forward letting the cable pull back, then drive hips forward to a standing position squeezing the glutes.$$ where name = 'Cable Pull-Through';
update exercises set description = $$Rear-foot-elevated split squat with a longer front foot stance and more forward lean to maximize glute over quad involvement. Lower to depth and drive through the heel to emphasize glute engagement.$$ where name = 'Bulgarian Split Squat (Glute Focus)';
update exercises set description = $$Bodyweight or cable glute isolation on all fours. From a kneeling position, kick one leg up and back, squeezing the glute at peak extension. Keep the knee bent to emphasize the glute over the hamstring.$$ where name = 'Donkey Kick';
update exercises set description = $$Machine exercise for the glute medius and minimus. Sit with thighs against the pads and push the knees apart against resistance. Control the movement back to center. Important for hip stability and glute width.$$ where name = 'Hip Abduction Machine';

-- CALVES
update exercises set description = $$Primary calf builder for the gastrocnemius. Stand on the edge of a platform or calf raise machine, lower your heels for a full stretch, then press up onto your toes as high as possible. Pause at the top and hold the contraction.$$ where name = 'Standing Calf Raise';
update exercises set description = $$Targets the soleus (deeper calf muscle) because the bent knee slackens the gastrocnemius. Sit with knees at 90°, pads across thighs, lower heels for a deep stretch, and drive up onto the toes.$$ where name = 'Seated Calf Raise';
update exercises set description = $$Calf raise performed on a leg press machine. Push the footplate with only the balls of your feet, lowering heels for a full stretch and pressing to a full contraction. Higher reps work well due to the stretched position.$$ where name = 'Leg Press Calf Raise';
update exercises set description = $$Standing calf raise holding dumbbells for added resistance. Stand on an elevated surface, let the heels drop below platform level for a stretch, and drive up onto the toes. Simple and effective for home or travel workouts.$$ where name = 'Dumbbell Calf Raise';
update exercises set description = $$Unilateral calf raise that doubles the load per leg compared to bilateral versions. Hold a wall for balance, lower the heel for a full stretch, and press through the ball of the foot to a full contraction. Addresses side imbalances.$$ where name = 'Single-Leg Calf Raise';
update exercises set description = $$A calf raise with a loaded hip-hinge position that stretches the gastrocnemius maximally. Hinge forward at the hips with a pad across your lower back for loading, and perform full-range calf raises. Strong stretch at the bottom.$$ where name = 'Donkey Calf Raise';

-- ABS
update exercises set description = $$Basic abdominal isolation. Lie on your back with knees bent, hands behind your head, and curl the shoulders off the floor by contracting the abs. Focus on spinal flexion — do not pull the neck. Lower with control.$$ where name = 'Crunch';
update exercises set description = $$Weighted abdominal exercise using a cable. Kneel, grip a rope attachment overhead, and crunch down, pulling the rib cage toward the hips. Do not pull with the arms — use only the abs. Allows progressive overload on the core.$$ where name = 'Cable Crunch';
update exercises set description = $$Advanced core exercise. Hang from a pull-up bar, raise your straight legs (or bent knees for regression) to hip height or beyond by contracting the hip flexors and abs. Avoid swinging and lower under control.$$ where name = 'Hanging Leg Raise';
update exercises set description = $$Floor version of the leg raise. Lie flat, place hands under your lower back for support, and raise straight legs to vertical while keeping the lower back pressed to the floor. Lower slowly without letting feet touch.$$ where name = 'Lying Leg Raise';
update exercises set description = $$Highly demanding core stability exercise. Kneel with the ab wheel under your shoulders, roll forward until your body is nearly parallel to the floor, then contract the abs to pull back to the start. Keep hips in line with the torso.$$ where name = 'Ab Wheel Rollout';
update exercises set description = $$Isometric core stability exercise. Hold a push-up position (or on forearms), keeping the body in a straight line from head to heels. Brace the abs and glutes throughout. Progress by extending hold time or adding instability.$$ where name = 'Plank';
update exercises set description = $$Sit-up performed on a decline bench for increased range of motion. Secure your feet, lower your torso back until nearly parallel, and curl back up using the abs. Add a plate for weight to increase difficulty.$$ where name = 'Decline Sit-Up';
update exercises set description = $$Rotational core exercise. Sit with knees bent and torso leaned back at ~45°, lift feet off the floor optionally, and rotate the torso side to side. Use a dumbbell, plate, or medicine ball for resistance.$$ where name = 'Russian Twist';
update exercises set description = $$Russian twist holding a dumbbell, plate, or medicine ball for added resistance. Same rotation mechanic — focus on twisting through the spine rather than just moving the arms, and keep control through the entire range.$$ where name = 'Weighted Russian Twist';
update exercises set description = $$Full-range sit-up with arms reaching toward the feet at the top. Start lying flat, curl up to fully seated while reaching hands toward toes, then lower with control. The reaching arm position increases abdominal activation.$$ where name = 'Reaching Sit-Up';
update exercises set description = $$Advanced full-body core exercise. Lie on a bench, grip it behind your head, raise the legs and hips until only the upper back touches, then lower the entire body as one rigid unit slowly toward the bench. Extremely demanding.$$ where name = 'Dragon Flag';
update exercises set description = $$Anti-rotation core exercise. Stand sideways to a cable machine, hold the handle at chest height, and press it straight out then return. The core must resist the rotational pull of the cable throughout. Great for core stability.$$ where name = 'Pallof Press';
update exercises set description = $$Core stability movement that trains anti-extension. Lie on your back, arms vertical and knees at 90°, then lower the opposite arm and leg toward the floor while keeping the lower back pressed down. Return and repeat on the other side.$$ where name = 'Dead Bug';
update exercises set description = $$Advanced crunch that lifts both legs and torso simultaneously. From a flat lying position, fold the body into a V-shape by bringing hands and feet together above the hips, then lower back down with control.$$ where name = 'V-Up';

-- TRAPS
update exercises set description = $$Primary trap builder. Hold a barbell at hip level with a double-overhand grip, shrug shoulders straight up toward your ears as high as possible, hold briefly at the top, and lower with control. No rolling — straight up and down.$$ where name = 'Barbell Shrug';
update exercises set description = $$Shrug variation with dumbbells held at your sides. Allows the arms to travel in a natural path and can be easier on the wrists. Same technique — shrug straight up, hold the contraction, and lower slowly.$$ where name = 'Dumbbell Shrug';
update exercises set description = $$Shrug using a cable machine for constant tension through the full range. Attach a bar to a low pulley, hold with arms extended, and shrug. The cable maintains tension at the bottom of the movement unlike free weights.$$ where name = 'Cable Shrug';
update exercises set description = $$Trap isolation on a dedicated shrug machine or modified from a seated row station. Machine shrugs remove the need to stabilize the weight, allowing pure focus on trap contraction and high-rep volume.$$ where name = 'Machine Shrug';
